server:
  port: 8761

spring:
  profiles:
    active: dev 
  application:
    name: spring-cloud-eureka

  cloud:
    inetutils:
      ignoredInterfaces:
        - docker0
        - veth.*
        - VM.*
      preferredNetworks:
        - 192.168

  security:
    user:
      name: root
      password: passw0rd